from streamlit import markdown, columns, subheader, write, divider, info

def display_home_page():
    markdown(
        '<div class="main-title">'
        '🤖 AI Interview Assistant'
        '</div>',
        unsafe_allow_html=True
    )

    markdown(
        '<div class="subtitle">'
        'Practice smarter. Get personalized AI feedback. '
        'Improve your interview performance.'
        '</div>',
        unsafe_allow_html=True
    )

    col1, col2, col3 = columns(3)

    with col1:
        markdown(
            '<div class="metric-card">',
            unsafe_allow_html=True
        )
        subheader("📄 Resume Analysis")
        write(
            "Analyze your resume and identify "
            "important skills and experience."
        )
        markdown("</div>", unsafe_allow_html=True)

    with col2:
        markdown(
            '<div class="metric-card">',
            unsafe_allow_html=True
        )
        subheader("🎯 AI Interview")
        write(
            "Practice personalized interview "
            "questions generated by AI."
        )
        markdown("</div>", unsafe_allow_html=True)

    with col3:
        markdown(
            '<div class="metric-card">',
            unsafe_allow_html=True
        )
        subheader("📊 Performance Report")
        write(
            "Understand your strengths and "
            "areas that need improvement."
        )
        markdown("</div>", unsafe_allow_html=True)

    divider()

    subheader("How It Works")

    steps = [
        "1️⃣ Upload your resume",
        "2️⃣ Configure your interview",
        "3️⃣ Answer AI-generated questions",
        "4️⃣ Receive evaluation",
        "5️⃣ Get personalized AI feedback"
    ]

    for step in steps:
        write(step)

    divider()

    info(
        "Start by uploading your resume from the "
        "**Resume** section."
    )